const drugData = {
    "M01AB": ["bumadizone", "etodolac", "lonazolac", "fentiazac", "acemetacin", "difenpiramide", "oxametacin", "proglumetacin", "ketorolac", "aceclofenac", "bufexamac", "indometacin", "combinations", "diclofenac"],
    "M01AE": ["ibuprofen", "naproxen", "ketoprofen", "fenoprofen", "fenbufen", "benoxaprofen", "suprofen", "pirprofen", "flurbiprofen", "indoprofen", "tiaprofenic", "acid", "oxaprozin", "ibuproxam", "dexibuprofen", "flunoxaprofen", "alminoprofen", "dexketoprofen", "naproxcinod", "loxoprofen", "pelubiprofen", "naproxen", "esomeprazole", "naproxen", "misoprostol", "naproxen", "diphenhydramine", "Meloxicam", "Celecoxib"],
    "N02BA": ["Acetylsalicylic", "acid", "Aloxiprin", "Choline", "salicylate", "Sodium", "salicylate", "Salicylamide", "Salsalate", "Ethenzamide", "Morpholine", "salicylate", "Dipyrocetyl", "Benorilate", "Diflunisal", "Potassium", "salicylate", "Guacetisal", "Carbasalate", "calcium", "Imidazole", "salicylate", "Aspirin"],
    "N02BE": ["Phenazone", "Metamizole", "Aminophenazone", "Propyphenazone", "Nifenazone", "Paracetamol", "Phenacetin", "Bucetin", "Propacetamol", "Tylenol"],
    "N05B": ["Diazepam", "Chlordiazepoxide", "Medazepam", "Oxazepam", "Potassium", "clorazepate", "Lorazepam", "Adinazolam", "Bromazepam", "Clobazam", "Ketazolam", "Prazepam", "Alprazolam", "Halazepam", "Pinazepam", "Camazepam", "Nordazepam", "Fludiazepam", "Ethyl", "loflazepate", "Etizolam", "Clotiazepam", "Cloxazolam", "Tofisopam", "Bentazepam", "Mexazolam", "Hydroxyzine", "Captodiame", "Meprobamate", "Emylcamate", "Mebutamate", "Benzoctamine", "Buspirone", "Mephenoxalone", "Gedocarnil", "Etifoxine", "Fabomotizole", "Lavandulae", "aetheroleum", "Clonazepam"],
    "N05C": ["Pentobarbital", "Amobarbital", "Butobarbital", "Barbital", "Aprobarbital", "Secobarbital", "Talbutal", "Vinylbital", "Vinbarbital", "Cyclobarbital", "Heptabarbital", "Reposal", "Methohexital", "Hexobarbital", "Thiopental", "Ethallobarbital", "Allobarbital", "Proxibarbal", "Chloral", "hydrate", "Chloralodol", "Acetylglycinamide", "chloral", "hydrate", "Dichloralphenazone", "Paraldehyde", "Flurazepam", "Nitrazepam", "Flunitrazepam", "Estazolam", "Triazolam", "Lormetazepam", "Temazepam", "Midazolam", "Brotizolam", "Quazepam", "Loprazolam", "Zolpidem", "Sertraline", "Escitalopram"],
    "R03": ["Epinephrine", "Isoprenaline", "Orciprenaline", "Salbutamol", "Terbutaline", "Fenoterol", "Rimiterol", "Hexoprenaline", "Isoetarine", "Pirbuterol", "Tretoquinol", "Carbuterol", "Tulobuterol", "Salmeterol", "Formoterol", "Clenbuterol", "Reproterol", "Procaterol", "Bitolterol", "Indacaterol", "Olodaterol", "Beclometasone", "Budesonide", "Flunisolide", "Betamethasone", "Fluticasone", "Triamcinolone", "Mometasone", "Ciclesonide", "Fluticasone furoate", "Ipratropium bromide", "Oxitropium bromide", "Stramoni preparations", "Tiotropium bromide", "Aclidinium bromide", "Glycopyrronium bromide", "Umeclidinium bromide", "Revefenacin", "Cromoglicic acid", "Nedocromil", "Fenspiride", "Ephedrine", "Methoxyphenamine", "Bambuterol", "Diprophylline", "Choline theophyllinate", "Proxyphylline", "Theophylline", "Aminophylline", "Etamiphylline", "Theobromine", "Bamifylline", "Acefylline piperazine", "Bufylline", "Doxofylline", "Mepyramine theophyllinacetate", "Zafirlukast", "Pranlukast", "Montelukast", "Ibudilast", "Amlexanox", "Eprozinol", "Omalizumab", "Seratrodast", "Roflumilast", "Reslizumab", "Mepolizumab", "Benralizumab", "Tezepelumab"],
    "R06": ["Bromazine", "Diphenhydramine", "Clemastine", "Chlorphenoxamine", "Diphenylpyraline", "Carbinoxamine", "Doxylamine", "Trimethobenzamide", "Dimenhydrinate", "Brompheniramine", "Dexchlorpheniramine", "Dimetindene", "Chlorphenamine", "Pheniramine", "Dexbrompheniramine", "Talastine", "Mepyramine", "Histapyrrodine", "Chloropyramine", "Tripelennamine", "Methapyrilene", "Thonzylamine", "Alimemazine", "Promethazine", "Thiethylperazine", "Methdilazine", "Hydroxyethylpromethazine", "Thiazinam", "Mequitazine", "Oxomemazine", "Isothipendyl", "Buclizine", "Cyclizine", "Chlorcyclizine", "Meclozine", "Oxatomide", "Cetirizine", "Levocetirizine", "Bamipine", "Cyproheptadine", "Thenalidine", "Phenindamine", "Antazoline", "Triprolidine", "Pyrrobutamine", "Azatadine", "Astemizole", "Terfenadine", "Loratadine", "Mebhydrolin", "Deptropine", "Ketotifen", "Acrivastine", "Azelastine", "Tritoqualine", "Ebastine", "Pimethixene", "Epinastine", "Mizolastine", "Fexofenadine", "Desloratadine", "Rupatadine", "Bilastine", "Quifenadine", "Sequifenadine", "Mebhydrolin", "Deptropine", "Ketotifen", "Acrivastine", "Azelastine", "Tritoqualine", "Ebastine", "Pimethixene", "Epinastine", "Mizolastine", "Fexofenadine", "Desloratadine", "Rupatadine", "Bilastine", "Quifenadine", "Sequifenadine", "Thenalidine", "Pyrrobutamine"]
};
export default drugData;


